In [40]:
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

Data collection and preprocessing

In [41]:
raw_mail_data = pd.read_csv("/content/sample_data/mail_data.csv")

In [42]:
raw_mail_data.head()

  Category                                            Message
0      ham  Go until jurong point, crazy.. Available only ...
1      ham                      Ok lar... Joking wif u oni...
2     spam  Free entry in 2 a wkly comp to win FA Cup fina...
3      ham  U dun say so early hor... U c already then say...
4      ham  Nah I don't think he goes to usf, he lives aro...

In [43]:
raw_mail_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5572 entries, 0 to 5571
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Category  5572 non-null   object
 1   Message   5572 non-null   object
dtypes: object(2)
memory usage: 87.2+ KB

In [44]:
raw_mail_data.shape

(5572, 2)

In [45]:
raw_mail_data.isnull().sum()

Category    0
Message     0
dtype: int64

Label Encoding

spam --> 0
nonspam --> 1

In [46]:
raw_mail_data.loc[raw_mail_data['Category']=='spam','Category',]=0
raw_mail_data.loc[raw_mail_data['Category']=='ham','Category',]=1

seperate feature and target

In [47]:
x = raw_mail_data['Message']
y = raw_mail_data['Category']

In [48]:
print(x)

0       Go until jurong point, crazy.. Available only ...
1                           Ok lar... Joking wif u oni...
2       Free entry in 2 a wkly comp to win FA Cup fina...
3       U dun say so early hor... U c already then say...
4       Nah I don't think he goes to usf, he lives aro...
                              ...
5567    This is the 2nd time we have tried 2 contact u...
5568                 Will ü b going to esplanade fr home?
5569    Pity, * was in mood for that. So...any other s...
5570    The guy did some bitching but I acted like i'd...
5571                           Rofl. Its true to its name
Name: Message, Length: 5572, dtype: object

In [49]:
print(y)

0       1
1       1
2       0
3       1
4       1
       ..
5567    0
5568    1
5569    1
5570    1
5571    1
Name: Category, Length: 5572, dtype: object

Train test split

In [50]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,stratify=y,random_state=3)

Feature extraction

In [51]:
# transform the text data to feature vectors that can be used as input for the logistic regresion model
feature_extraction = TfidfVectorizer(min_df=1,stop_words='english',lowercase=True)

In [52]:
x_train_features = feature_extraction.fit_transform(x_train)
x_test_features =feature_extraction.transform(x_test)

# convert y_train and y_test values as integers
y_train = y_train.astype('int')
y_test = y_test.astype('int')

In [53]:
print(x_train_features)

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 34678 stored elements and shape (4457, 7493)>
  Coords	Values
  (0, 2353)	0.28101404009316056
  (0, 3806)	0.28101404009316056
  (0, 1857)	0.17073786814794129
  (0, 1193)	0.22908400928709988
  (0, 3113)	0.28101404009316056
  (0, 3627)	0.25144905621529934
  (0, 6330)	0.24059246244542992
  (0, 1540)	0.17407870571957915
  (0, 2644)	0.28101404009316056
  (0, 5029)	0.17467075796896542
  (0, 4306)	0.26793132631329497
  (0, 421)	0.25144905621529934
  (0, 4557)	0.28101404009316056
  (0, 6468)	0.26793132631329497
  (0, 1657)	0.28101404009316056
  (0, 0)	0.23628394623676158
  (1, 3982)	0.4167622750027118
  (1, 5911)	0.2761926296686631
  (1, 3941)	0.20702870014136815
  (1, 1969)	0.1749293187718031
  (1, 6553)	0.4722950153731612
  (1, 5947)	0.24356944504246256
  (1, 3948)	0.2761926296686631
  (1, 2113)	0.1985161464110967
  (1, 3828)	0.13684128003316173
  :	:
  (4456, 5091)	0.1743505991070133
  (4456, 7339)	0.13767285254208542
  (4456, 2414)	0.17857780047236718
  (4456, 3262)	0.16745892210920407
  (4456, 7434)	0.1566807006510762
  (4456, 4120)	0.11213756070741854
  (4456, 3147)	0.11213756070741854
  (4456, 5430)	0.2902170940779003
  (4456, 3362)	0.13296028402451
  (4456, 1571)	0.1695693884304312
  (4456, 4975)	0.15534275099802256
  (4456, 1290)	0.1566807006510762
  (4456, 2236)	0.17068883072653956
  (4456, 2690)	0.19758564858135794
  (4456, 4765)	0.1730749026661772
  (4456, 5420)	0.19758564858135794
  (4456, 4878)	0.2137042449780485
  (4456, 5447)	0.2198234053076842
  (4456, 6646)	0.22771237505351186
  (4456, 6568)	0.23883125341667502
  (4456, 2138)	0.23883125341667502
  (4456, 3913)	0.23883125341667502
  (4456, 1186)	0.23883125341667502
  (4456, 877)	0.23883125341667502
  (4456, 7001)	0.23883125341667502

Model training

Logistic Regression

In [54]:
model = LogisticRegression()

In [55]:
model.fit(x_train_features,y_train)

LogisticRegression()

model evaluation

In [58]:
# prediction on training data
prediction_train = model.predict(x_train_features)
accuracy_score_train = accuracy_score(y_train,prediction_train)
print("Training accuracy: ",accuracy_score_train)

Training accuracy:  0.9667938074938299

In [59]:
# prediction on test data
prediction_test = model.predict(x_test_features)
accuracy_score_test = accuracy_score(y_test,prediction_test)
print("Test accuracy: ",accuracy_score_test)

Test accuracy:  0.9713004484304932

Building a predictive system

In [60]:
mail = ["Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat..."]
input_data_features = feature_extraction.transform(mail)
prediction = model.predict(input_data_features)
if(prediction[0]==0):
  print("Spam")
else:
  print("Ham")

Ham